# Generated by Django 3.1.6 on 2021-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_kcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='kcal',
            field=models.IntegerField(null=True),
        ),
    ]
