# Generated by Django 3.1.6 on 2021-03-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_document_keyword_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='termFrequency',
            field=models.FloatField(default=0),
        ),
    ]
