# Generated by Django 3.1.7 on 2021-04-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210324_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('measurement', models.CharField(choices=[('G', 'g'), ('L', 'L'), ('KG', 'kg'), ('DL', 'dL'), ('ML', 'mL'), ('TaS', 'Tablespoon'), ('TeS', 'Teaspoon'), ('C', 'Cup')], default='G', max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
