# Generated by Django 3.1.7 on 2021-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_num_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='numKeywords',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='docFrequency',
            field=models.FloatField(default=1),
        ),
    ]
