# Generated by Django 3.1.6 on 2021-04-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210416_1236'),
        ('recipes', '0013_auto_20210417_1227'),
    ]

    operations = [
    ]
