# Generated by Django 3.1.7 on 2021-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210420_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('P', ''), ('G', 'g'), ('L', 'L'), ('KG', 'kg'), ('DL', 'dL'), ('ML', 'mL'), ('TaS', 'tablespoons'), ('TeS', 'teaspoons'), ('C', 'cups'), ('B', 'boats'), ('O', 'ounces'), ('S', 'slices'), ('PCH', 'pinch'), ('PD', 'pounds')], default='P', max_length=10),
        ),
    ]
