# Generated by Django 3.1.7 on 2021-04-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipe_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='numKeywords',
        ),
        migrations.RemoveField(
            model_name='word',
            name='docFrequency',
        ),
    ]
