# Generated by Django 3.1.7 on 2021-04-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210223_0044'),
        ('recipes', '0019_auto_20210427_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fooduser')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fooduser')),
            ],
        ),
    ]
