# Generated by Django 3.1.6 on 2021-04-30 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210223_0044'),
        ('recipes', '0020_keywordscore_recipescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='recently_recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(default=datetime.date(2021, 5, 3))),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fooduser')),
            ],
        ),
    ]
