# Generated by Django 3.1.7 on 2021-05-04 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210223_0044'),
        ('recipes', '0021_recently_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recently_recommended',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2021, 5, 7)),
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.fooduser')),
            ],
        ),
    ]
